### PR TITLE
darknet recipe improvement

### PR DESCRIPTION
**Pull request by uilianries**
Consider it as a review.

- As the Darkweb project does not offer tags, you should use a commit instead, and the date of that commit. We use date because you can sort before searching.
- OpenCV is optional, but is not available yet. All recipes from conan-community or Bincrafters are not valid.

- [ ] I've read the [guidelines](https://github.com/conan-io/conan-center-index/wiki#how-to-submit-a-pull-request) for contributing.
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guides for Python code in the recipes.
- [ ] I've used the [latest](https://github.com/conan-io/conan/releases/latest) Conan client version.
- [ ] I've tried at least one configuration locally with the
      [conan-center hook](https://github.com/conan-io/hooks.git) activated.

### CODE REVIEW

**Comment by PierreRamoin** [comment]
Thanks for the feedback @uilianries !

I will do the change for the commit/date !
About OpenCV, should I remove entirely the option? I really need it for the project I work on with darknet so it's not really an option for me...

**Comment by uilianries** [comment]
I see, we have the OpenCV package from Conan Community, which was made by @SSE4. I don't know his plans for moving OpenCV to CCI.

**Comment by PierreRamoin** [comment]
Ok. In the meantime what should I do?
For the commit/date, the version should be like: 
2018-09-14-61c9d02ec461e30d55762ec7669d6a1d3c356fb2 ? Or the date should be the version and the commit hash the download link?

**Comment by PierreRamoin** [comment]
Sorry I didn't seen you already did it on the PR!! Thanks a lot!

**Pull request merged**
